### ISSUE TITLE
ERR_CONNECTION_REFUSED when hitting the container through the node middleware.

### ISSUE THREAD

**Issue by fxalvarezd** [nkonev/rendertron-docker#1]
I'm building and running the container like this,  and it runs fine:
```
docker build -t rendertronfx .

docker run -it -p 3000:3000 rendertronfx

> rendertron@2.0.1 start /opt/rendertron
> node build/rendertron.js

Listening on port 3000
```

Then I'm testing it with the node middleware and when I hit the route, the middleware kicks in and I get this error on the container:

```
  <-- GET /render/http%3A%2F%2Flocalhost%3A3001%2Fhomes-for-sale%2F8110-Ranch-Road-2222-Apt-69_Austin_TX_78730_2058447%2Ftx_actris-2058447?wc-inject-shadydom=true
Error: net::ERR_CONNECTION_REFUSED at http://localhost:3001/homes-for-sale/8110-Ranch-Road-2222-Apt-69_Austin_TX_78730_2058447/tx_actris-2058447
    at navigate (/opt/rendertron/node_modules/puppeteer/lib/Page.js:622:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
response does not exist
  --> GET /render/http%3A%2F%2Flocalhost%3A3001%2Fxxx...xxx?wc-inject-shadydom=true 400 73ms 0b
```

Any ideas?

Thanks!

**Comment by nkonev** [comment]
Just enter to your container (docker exec -it youcontainer sh)

Next try to invoke your url with wget or curl.

If it returns error then you should check you server, docker network, port forwarding/binding and so on.

Nevertheless, you most probably got mistake with localhost host.


Upd: port 3001

**Comment by fxalvarezd** [comment]
Thx for the reply, I'll definitely try that.
My app is actually running on port 3001 because rendertron is running on port 3000.
